port: 8083
mongo:
  user: hanajung
  pass: test1234
  host: golang_api_db:27017
  db: document
mysql:
  user: interfacedev
  pass: Interface@APIDev
  db: apishopdev
  protocal: tcp(172.22.228.224:3306)
elastics:
  url: http://172.22.228.224:9200
logger:
  filename: logger.log