version: "3.7"
services:
  database:
    image: mongo:4.4
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=root
      # - MONGO_INITDB_ROOT_PASSWORD=password
      # - MONGO_INITDB_DATABASE=dd_hakka
      # - MONGO_INITDB_USERNAME=dd_hakka
      # - MONGO_INITDB_PASSWORD=password
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=example
      - MONGO_INITDB_USERNAME=kajame
      - MONGO_INITDB_PASSWORD=111111
    volumes:
      # - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      # - ./db:/data/db
      - ./mongodbdata:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro